### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by tanilserbes** [gorgias/gtm-chat#4]
Hi,

I am getting an error on console. I implemented gorgias chat by using gtm-chat but it somehow gives an error. 
Can you have a look please?

<img width="424" alt="2022-10-13_14h30_32" src="https://user-images.githubusercontent.com/61015092/195610329-3a3a8f58-48be-46a6-8467-5e2b66426421.png">

Thanks
Tanil

**Comment by juancarlosqr** [comment]
Hi @tanilserbes, Juan Carlos from the Gorgias Chat team here. Apologies for our delay in getting back to you.

Not sure if the issue still persists, but if it does, please reach out using our official support channels available in your Gorgias dashboard so we can take a close look, having the full context of your situation.

Thanks for reporting
